### ISSUE TITLE
Plz modify my EA template 

### ISSUE THREAD

**Issue by MAWFOREX** [sibvic/mq4-templates#1]
[AAUTO.zip](https://github.com/indrawdev/CustomEA/files/5080788/AAUTO.zip)
I have EA template which automate buffer based indicators . I want to add more advanced features in that to make that more advanced. 

I want to add SL on Previous candle and Close Order on basis Of time e.g 10 ,11,12, 20, 21 minutes etc![IMG_20200816_195438_357.jpg](https://user-images.githubusercontent.com/69757543/90336574-56d77400-dffa-11ea-9a77-4298a5c7c5ac.jpg)[](

ZIP file is attached inside that is EA template.

If u will add more features to make it a complete EA template for buffer based indicator.   I will be thankful to u
Hope u will add much more which even my mind doesn't think about

**Comment by sibvic** [comment]
Post request on http://fxcodebase.com
