### ISSUE TITLE
6 errors -  undeclared identifier at the new AccountStatistics 

### ISSUE THREAD

**Issue by h0ttz** [sibvic/mq4-templates#2]
https://github.com/sibvic/mq4-templates/blob/81ec92e336ce11e3177bf8573b0a6196cd912285/Templates/EA_Base.mq4#L683
https://github.com/sibvic/mq4-templates/blob/9ad44209a01deb815dec2c0afe979a9d26a0d82b/snippets/AccountStatistics.mq4#L31
https://github.com/sibvic/mq4-templates/blob/9ad44209a01deb815dec2c0afe979a9d26a0d82b/snippets/AccountStatistics.mq4#L33
https://github.com/sibvic/mq4-templates/blob/9ad44209a01deb815dec2c0afe979a9d26a0d82b/snippets/AccountStatistics.mq4#L37
https://github.com/sibvic/mq4-templates/blob/9ad44209a01deb815dec2c0afe979a9d26a0d82b/snippets/AccountStatistics.mq4#L39
https://github.com/sibvic/mq4-templates/blob/9ad44209a01deb815dec2c0afe979a9d26a0d82b/snippets/AccountStatistics.mq4#L41

'AccountStatistics' - wrong parameters count
'last_tp' - undeclared identifier
'last_sl' - undeclared identifier
'last_signal' - undeclared identifier
'last_price' - undeclared identifier
'last_time' - undeclared identifier
6 errors, 0 warnings

![image](https://user-images.githubusercontent.com/2601312/94645324-88aa4e80-02b9-11eb-9830-0a8b4d801741.png)

**Comment by sibvic** [comment]
Fixed
