### ISSUE TITLE
Comprehensive Doc

### ISSUE THREAD

**Issue by Ahmad138** [sibvic/mq4-templates#3]
Hi,
I love the work you have done and/or are doing at the moment with the provision to the free market. But how do I get comprehensive documentation of your code instead of me rummaging in your code files? I want to understand your structure and if possible improve on it.

Thanks.
P.S: is it possible to restructure the code base as I had to do some modification just to compile the base template.

**Comment by sibvic** [comment]
There is too much files to describe. It's better to do it in other way: tell me what you want to do and I will make a documentation for it.
