### ISSUE TITLE
Help me for fix MT4

### ISSUE THREAD

**Issue by Theycallmekalle** [sibvic/mq4-templates#8]
Hello, have a good time
I wanted to talk to you about one of your programs, "Super Arrow EA"
I ran it in all time frames, but it doesn't run at all, no special error or anything. Even for 2 weeks, it was running 24 hours a day, but it did not make any transactions. Is there an error in its source code that I should fix?
And I also tested the program in its default mode, but I didn't get an answer
The indicator is not updated at all and I have to refresh it myself so that it shows the buy or sell arrow. I would be grateful if you could help me.

**Comment by sibvic** [comment]
It's not related to the templates

**Comment by Theycallmekalle** [comment]
So, do you have a special configuration for this? To open trades
